sudo: false # don't need root access on Travis-CI (builds faster without sudo!)

language: node_js # elm is installed from npm (see install below)
node_js: node     # use "latest" version of Node.js

# See https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.travis.yml
addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories: # so subsequent builds run faster
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - $HOME/.npm # https://stackoverflow.com/a/42523517/1148249

before_install:
  - uname -a # print the *exact* operating system/kernel version

install:
  - npm install

script:
  # https://github.com/elm/compiler/issues/1473#issuecomment-464126168
  - npx elm make +RTS -N2
  - npm test
